#!/usr/bin/env bash
set -eu
tx="$1"
endtx="${2:-}"
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
d="${SCRIPT_DIR}/data-manual/daisy"
mkdir -p "$d"
f="$d/$tx"
rm -f "$f"
tx_index="$(curl -s "https://blockchain.info/tx/$tx?format=json" | jq '.tx_index')"
while true; do
  json="$(curl -s "https://blockchain.info/tx/$tx_index?format=json")"
  # Fails if there are no spent outputs.
  if tx_index="$(printf %s "$json" | jq -r '[.out[] | select(.spent == true)][0].spending_outpoints[0].tx_index')"; then
    unspent_indices="$(printf %s "$json" | jq -r '.out | map(.spent == false) | indices(true) | join(" ")')"
    tx="$(printf %s "$json" | jq -r '.hash')"
    [ -z "$unspent_indices" ] && break
    printf "${tx} ${unspent_indices}\n" | tee -a $f
    if [ -n "$endtx" ] && [ "$tx" = "$endtx" ]; then
      break
    fi
  else
    break
  fi
  sleep 0.1
done
